=== MegaMek/MekWars/MekWars/server-dist/data/factions.dtd
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Jon Schattke (Scahttke Computer Services) --><!--DTD generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)--><!ELEMENT DOCUMENT (MEGAMEKNETFACTIONDATA)><!ELEMENT MEGAMEKNETFACTIONDATA (FACTION+)><!ELEMENT FACTION (NAME, MONEY, COLOR, ABBREVIATION, ISMERCENARY, LOGO, BASEGUNNER, BASEPILOT, CONQUERABLE, INHOUSEATTACKS, MAYUSEBM, HOUSEPLAYERCOLOR, DEFECTTO, DEFECTFROM, ISNEWBIE, ID)><!ELEMENT NAME (#PCDATA)><!ELEMENT MONEY (#PCDATA)><!ELEMENT COLOR (#PCDATA)><!ELEMENT ABBREVIATION (#PCDATA)><!ELEMENT ISMERCENARY (#PCDATA)><!ELEMENT LOGO (#PCDATA)><!ELEMENT BASEGUNNER (#PCDATA)><!ELEMENT BASEPILOT (#PCDATA)><!ELEMENT CONQUERABLE (#PCDATA)><!ELEMENT INHOUSEATTACKS (#PCDATA)><!ELEMENT MAYUSEBM (#PCDATA)><!ELEMENT HOUSEPLAYERCOLOR (#PCDATA)><!ELEMENT DEFECTTO (#PCDATA)><!ELEMENT DEFECTFROM (#PCDATA)><!ELEMENT ISNEWBIE (#PCDATA)><!ELEMENT ID (#PCDATA)>

=== MegaMek/MekWars/server-dist/data/factions.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DOCUMENT SYSTEM "factions.dtd">
<DOCUMENT>
	<MEGAMEKNETFACTIONDATA>
		<FACTION>
			<NAME>Davion</NAME>
			<MONEY>180</MONEY>
			<COLOR>#808000</COLOR>
			<ABBREVIATION>D</ABBREVIATION>
			<ISMERCENARY>false</ISMERCENARY>
			<LOGO>http://www.megamek.com/NoLogo.jpg</LOGO>
			<BASEGUNNER>4</BASEGUNNER>
			<BASEPILOT>5</BASEPILOT>
			<CONQUERABLE>true</CONQUERABLE>
			<INHOUSEATTACKS>false</INHOUSEATTACKS>
			<MAYUSEBM>true</MAYUSEBM>
			<HOUSEPLAYERCOLOR>#808000</HOUSEPLAYERCOLOR>
			<DEFECTTO>true</DEFECTTO>
			<DEFECTFROM>true</DEFECTFROM>
			<ISNEWBIE>false</ISNEWBIE>
			<ID>0</ID>
		</FACTION>
		<FACTION>
			<NAME>Steiner</NAME>
			<MONEY>180</MONEY>
			<COLOR>#0000ff</COLOR>
			<ABBREVIATION>S</ABBREVIATION>
			<ISMERCENARY>false</ISMERCENARY>
			<LOGO>http://www.megamek.com/NoLogo.jpg</LOGO>
			<BASEGUNNER>4</BASEGUNNER>
			<BASEPILOT>5</BASEPILOT>
			<CONQUERABLE>true</CONQUERABLE>
			<INHOUSEATTACKS>false</INHOUSEATTACKS>
			<MAYUSEBM>true</MAYUSEBM>
			<HOUSEPLAYERCOLOR>#0000ff</HOUSEPLAYERCOLOR>
			<DEFECTTO>true</DEFECTTO>
			<DEFECTFROM>true</DEFECTFROM>
			<ISNEWBIE>false</ISNEWBIE>
			<ID>1</ID>
		</FACTION>
		<FACTION>
			<NAME>Liao</NAME>
			<MONEY>180</MONEY>
			<COLOR>#004000</COLOR>
			<ABBREVIATION>L</ABBREVIATION>
			<ISMERCENARY>false</ISMERCENARY>
			<LOGO>http://www.megamek.com/NoLogo.jpg</LOGO>
			<BASEGUNNER>4</BASEGUNNER>
			<BASEPILOT>5</BASEPILOT>
			<CONQUERABLE>true</CONQUERABLE>
			<INHOUSEATTACKS>false</INHOUSEATTACKS>
			<MAYUSEBM>true</MAYUSEBM>
			<HOUSEPLAYERCOLOR>#004000</HOUSEPLAYERCOLOR>
			<DEFECTTO>true</DEFECTTO>
			<DEFECTFROM>true</DEFECTFROM>
			<ISNEWBIE>false</ISNEWBIE>
			<ID>2</ID>
		</FACTION>
		<FACTION>
			<NAME>Marik</NAME>
			<MONEY>180</MONEY>
			<COLOR>#800080</COLOR>
			<ABBREVIATION>M</ABBREVIATION>
			<ISMERCENARY>false</ISMERCENARY>
			<LOGO>http://www.megamek.com/NoLogo.jpg</LOGO>
			<BASEGUNNER>4</BASEGUNNER>
			<BASEPILOT>5</BASEPILOT>
			<CONQUERABLE>true</CONQUERABLE>
			<INHOUSEATTACKS>false</INHOUSEATTACKS>
			<MAYUSEBM>true</MAYUSEBM>
			<HOUSEPLAYERCOLOR>#ff0000</HOUSEPLAYERCOLOR>
			<DEFECTTO>true</DEFECTTO>
			<DEFECTFROM>true</DEFECTFROM>
			<ISNEWBIE>false</ISNEWBIE>
			<ID>3</ID>
		</FACTION>
		<FACTION>
			<NAME>Kurita</NAME>
			<MONEY>180</MONEY>
			<COLOR>#ff0000</COLOR>
			<ABBREVIATION>K</ABBREVIATION>
			<ISMERCENARY>false</ISMERCENARY>
			<LOGO>http://www.megamek.com/NoLogo.jpg</LOGO>
			<BASEGUNNER>4</BASEGUNNER>
			<BASEPILOT>5</BASEPILOT>
			<CONQUERABLE>true</CONQUERABLE>
			<INHOUSEATTACKS>false</INHOUSEATTACKS>
			<MAYUSEBM>true</MAYUSEBM>
			<HOUSEPLAYERCOLOR>#ff0000</HOUSEPLAYERCOLOR>
			<DEFECTTO>true</DEFECTTO>
			<DEFECTFROM>true</DEFECTFROM>
			<ISNEWBIE>false</ISNEWBIE>
			<ID>4</ID>
		</FACTION>
		<FACTION>
			<NAME>Periphery</NAME>
			<MONEY>180</MONEY>
			<COLOR>#333333</COLOR>
			<ABBREVIATION>P</ABBREVIATION>
			<ISMERCENARY>false</ISMERCENARY>
			<LOGO>http://www.megamek.com/NoLogo.jpg</LOGO>
			<BASEGUNNER>4</BASEGUNNER>
			<BASEPILOT>5</BASEPILOT>
			<CONQUERABLE>true</CONQUERABLE>
			<INHOUSEATTACKS>false</INHOUSEATTACKS>
			<MAYUSEBM>true</MAYUSEBM>
			<HOUSEPLAYERCOLOR>#ff0000</HOUSEPLAYERCOLOR>
			<DEFECTTO>true</DEFECTTO>
			<DEFECTFROM>true</DEFECTFROM>
			<ISNEWBIE>false</ISNEWBIE>
			<ID>5</ID>
		</FACTION>
		<FACTION>
			<NAME>Northwind Highlanders</NAME>
			<MONEY>180</MONEY>
			<COLOR>#008000</COLOR>
			<ABBREVIATION>HL</ABBREVIATION>
			<ISMERCENARY>true</ISMERCENARY>
			<LOGO>http://www.megamek.com/NoLogo.jpg</LOGO>
			<BASEGUNNER>4</BASEGUNNER>
			<BASEPILOT>5</BASEPILOT>
			<CONQUERABLE>true</CONQUERABLE>
			<INHOUSEATTACKS>false</INHOUSEATTACKS>
			<MAYUSEBM>true</MAYUSEBM>
			<HOUSEPLAYERCOLOR>#ff0000</HOUSEPLAYERCOLOR>
			<DEFECTTO>true</DEFECTTO>
			<DEFECTFROM>true</DEFECTFROM>
			<ISNEWBIE>false</ISNEWBIE>
			<ID>6</ID>
		</FACTION>
		<FACTION>
			<NAME>Wolfs Dragoons</NAME>
			<MONEY>180</MONEY>
			<COLOR>#800000</COLOR>
			<ABBREVIATION>WD</ABBREVIATION>
			<ISMERCENARY>true</ISMERCENARY>
			<LOGO>http://www.megamek.com/NoLogo.jpg</LOGO>
			<BASEGUNNER>4</BASEGUNNER>
			<BASEPILOT>5</BASEPILOT>
			<CONQUERABLE>true</CONQUERABLE>
			<INHOUSEATTACKS>false</INHOUSEATTACKS>
			<MAYUSEBM>true</MAYUSEBM>
			<HOUSEPLAYERCOLOR>#ff0000</HOUSEPLAYERCOLOR>
			<DEFECTTO>true</DEFECTTO>
			<DEFECTFROM>true</DEFECTFROM>
			<ISNEWBIE>false</ISNEWBIE>
			<ID>7</ID>
		</FACTION>
		<FACTION>
			<NAME>Hansens Roughriders</NAME>
			<MONEY>180</MONEY>
			<COLOR>#b0c4de</COLOR>
			<ABBREVIATION>HRR</ABBREVIATION>
			<ISMERCENARY>true</ISMERCENARY>
			<LOGO>http://www.megamek.com/NoLogo.jpg</LOGO>
			<BASEGUNNER>4</BASEGUNNER>
			<BASEPILOT>5</BASEPILOT>
			<CONQUERABLE>true</CONQUERABLE>
			<INHOUSEATTACKS>false</INHOUSEATTACKS>
			<MAYUSEBM>true</MAYUSEBM>
			<HOUSEPLAYERCOLOR>#ff0000</HOUSEPLAYERCOLOR>
			<DEFECTTO>true</DEFECTTO>
			<DEFECTFROM>true</DEFECTFROM>
			<ISNEWBIE>false</ISNEWBIE>
			<ID>8</ID>
		</FACTION>
		<FACTION>
			<NAME>Kell Hounds</NAME>
			<MONEY>180</MONEY>
			<COLOR>#990000</COLOR>
			<ABBREVIATION>KH</ABBREVIATION>
			<ISMERCENARY>true</ISMERCENARY>
			<LOGO>http://www.megamek.com/NoLogo.jpg</LOGO>
			<BASEGUNNER>4</BASEGUNNER>
			<BASEPILOT>5</BASEPILOT>
			<CONQUERABLE>true</CONQUERABLE>
			<INHOUSEATTACKS>false</INHOUSEATTACKS>
			<MAYUSEBM>true</MAYUSEBM>
			<HOUSEPLAYERCOLOR>#ff0000</HOUSEPLAYERCOLOR>
			<DEFECTTO>true</DEFECTTO>
			<DEFECTFROM>true</DEFECTFROM>
			<ISNEWBIE>false</ISNEWBIE>
			<ID>9</ID>
		</FACTION>
		<FACTION>
			<NAME>Gray Death Legion</NAME>
			<MONEY>180</MONEY>
			<COLOR>#990000</COLOR>
			<ABBREVIATION>GDL</ABBREVIATION>
			<ISMERCENARY>true</ISMERCENARY>
			<LOGO>http://www.megamek.com/NoLogo.jpg</LOGO>
			<BASEGUNNER>4</BASEGUNNER>
			<BASEPILOT>5</BASEPILOT>
			<CONQUERABLE>true</CONQUERABLE>
			<INHOUSEATTACKS>false</INHOUSEATTACKS>
			<MAYUSEBM>true</MAYUSEBM>
			<HOUSEPLAYERCOLOR>#ff0000</HOUSEPLAYERCOLOR>
			<DEFECTTO>true</DEFECTTO>
			<DEFECTFROM>true</DEFECTFROM>
			<ISNEWBIE>false</ISNEWBIE>
			<ID>10</ID>
		</FACTION>
		<FACTION>
			<NAME>Comstar</NAME>
			<MONEY>180</MONEY>
			<COLOR>#663300</COLOR>
			<ABBREVIATION>COM</ABBREVIATION>
			<ISMERCENARY>false</ISMERCENARY>
			<LOGO>http://www.megamek.com/NoLogo.jpg</LOGO>
			<BASEGUNNER>4</BASEGUNNER>
			<BASEPILOT>5</BASEPILOT>
			<CONQUERABLE>true</CONQUERABLE>
			<INHOUSEATTACKS>false</INHOUSEATTACKS>
			<MAYUSEBM>true</MAYUSEBM>
			<HOUSEPLAYERCOLOR>#ff0000</HOUSEPLAYERCOLOR>
			<DEFECTTO>true</DEFECTTO>
			<DEFECTFROM>true</DEFECTFROM>
			<ISNEWBIE>false</ISNEWBIE>
			<ID>11</ID>
		</FACTION>
		<FACTION>
			<NAME>Solaris Training Company</NAME>
			<MONEY>180</MONEY>
			<COLOR>#33CCCC</COLOR>
			<ABBREVIATION>SOL</ABBREVIATION>
			<ISMERCENARY>false</ISMERCENARY>
			<LOGO>http://www.megamek.com/NoLogo.jpg</LOGO>
			<BASEGUNNER>4</BASEGUNNER>
			<BASEPILOT>5</BASEPILOT>
			<CONQUERABLE>false</CONQUERABLE>
			<INHOUSEATTACKS>true</INHOUSEATTACKS>
			<MAYUSEBM>false</MAYUSEBM>
			<HOUSEPLAYERCOLOR>#33CCCC</HOUSEPLAYERCOLOR>
			<DEFECTTO>false</DEFECTTO>
			<DEFECTFROM>true</DEFECTFROM>
			<ISNEWBIE>true</ISNEWBIE>
			<ID>12</ID>
		</FACTION>
	</MEGAMEKNETFACTIONDATA>
</DOCUMENT>
