=== MegaMek/MekWars/MekWars/server-dist/data/terrain.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by FreeUser (FreeUser Inc.) -->
<!--DTD generated by XML Spy v4.3 U (http://www.xmlspy.com)-->
<!ELEMENT ALGORITHM (#PCDATA)>
<!ELEMENT CRATERMAXNUM (#PCDATA)>
<!ELEMENT CRATERMAXRADIUS (#PCDATA)>
<!ELEMENT CRATERMINNUM (#PCDATA)>
<!ELEMENT CRATERMINRADIUS (#PCDATA)>
<!ELEMENT CRATERPROB (#PCDATA)>
<!ELEMENT DOCUMENT (MEGAMEKNETTERRAINDATA)>
<!ELEMENT ENVIRONMENT (STATICMAP*, MAPNAME*, XMAP*, YMAP*, XBOARD*, YBOARD*, CRATERPROB*, CRATERMINNUM*, CRATERMAXNUM*, CRATERMINRADIUS*, CRATERMAXRADIUS*, HILLYNESS*, HILLELEVATIONRANGE*, HILLINVERTPROB*, WATERMINSPOTS*, WATERMAXSPOTS*, WATERMINHEXES*, WATERMAXHEXES*, WATERDEEPPROB*, FORESTMINSPOTS*, FORESTMAXSPOTS*, FORESTMINHEXES*, FORESTMAXHEXES*, FORESTHEAVYPROB*, ROUGHMINSPOTS*, ROUGHMAXSPOTS*, ROUGHMINHEXES*, ROUGHMAXHEXES*, ROADPROB*, CLIFFPROB*, RIVERPROB*, ALGORITHM*, SWAMPMINSPOTS*, SWAMPMAXSPOTS*, SWAMPMINHEXES*, SWAMPMAXHEXES*, PAVEMENTMINSPOTS*, PAVEMENTMAXSPOTS*, PAVEMENTMINHEXES*, PAVEMENTMAXHEXES*, ICEMINSPOTS*, ICEMAXSPOTS*, ICEMINHEXES*, ICEMAXHEXES*, RUBBLEMINSPOTS*, RUBBLEMAXSPOTS*, RUBBLEMINHEXES*, RUBBLEMAXHEXES*, SANDMINSPOTS*, SANDMAXSPOTS*, SANDMINHEXES*, SANDMAXHEXES*, PLANTEDFIELDMINSPOTS*, PLANTEDFIELDMAXSPOTS*, PLANTEDFIELDMINHEXES*, PLANTEDFIELDMAXHEXES*, FORTIFIEDMINSPOTS*, FORTIFIEDMAXSPOTS*, FORTIFIEDMINHEXES*, FORTIFIEDMAXHEXES*, CITYBLOCKS*, CITYTYPE*, MOUNTPEAKS*, MOUNTWIDTHMIN*, MOUNTWIDTHMAX*, MOUNTHEIGHTMIN*, MOUNTHEIGHTMAX*, MOUNTSTYLE*, MINCF*, MAXCF*, MINFLOORS*, MAXFLOORS*, CITYDENSITY*, FXMOD*, PROBFORESTFIRE*, PROBFREEZE*, PROBFLOOD*, PROBDROUGHT*, THEME?)>
<!ELEMENT ENVIRONMENTPROBABILITY (#PCDATA)>
<!ELEMENT FORESTHEAVYPROB (#PCDATA)>
<!ELEMENT FORESTMAXHEXES (#PCDATA)>
<!ELEMENT FORESTMAXSPOTS (#PCDATA)>
<!ELEMENT FORESTMINHEXES (#PCDATA)>
<!ELEMENT FORESTMINSPOTS (#PCDATA)>
<!ELEMENT HILLELEVATIONRANGE (#PCDATA)>
<!ELEMENT HILLINVERTPROB (#PCDATA)>
<!ELEMENT HILLYNESS (#PCDATA)>
<!ELEMENT MEGAMEKNETTERRAINDATA (TERRAIN+)>
<!ELEMENT NAME (#PCDATA)>
<!ELEMENT RIVERPROB (#PCDATA)>
<!ELEMENT ROADPROB (#PCDATA)>
<!ELEMENT ROUGHMAXHEXES (#PCDATA)>
<!ELEMENT ROUGHMAXSPOTS (#PCDATA)>
<!ELEMENT ROUGHMINHEXES (#PCDATA)>
<!ELEMENT ROUGHMINSPOTS (#PCDATA)>
<!ELEMENT TERRAIN (NAME, ENVIRONMENT)>
<!ELEMENT WATERDEEPPROB (#PCDATA)>
<!ELEMENT WATERMAXHEXES (#PCDATA)>
<!ELEMENT WATERMAXSPOTS (#PCDATA)>
<!ELEMENT WATERMINHEXES (#PCDATA)>
<!ELEMENT WATERMINSPOTS (#PCDATA)>
<!ELEMENT SWAMPMINSPOTS (#PCDATA)>
<!ELEMENT SWAMPMAXSPOTS (#PCDATA)>
<!ELEMENT SWAMPMINHEXES (#PCDATA)>
<!ELEMENT SWAMPMAXHEXES (#PCDATA)>
<!ELEMENT PAVEMENTMINSPOTS (#PCDATA)>
<!ELEMENT PAVEMENTMAXSPOTS (#PCDATA)>
<!ELEMENT PAVEMENTMINHEXES (#PCDATA)>
<!ELEMENT PAVEMENTMAXHEXES (#PCDATA)>
<!ELEMENT ICEMINSPOTS (#PCDATA)>
<!ELEMENT ICEMAXSPOTS (#PCDATA)>
<!ELEMENT ICEMINHEXES (#PCDATA)>
<!ELEMENT ICEMAXHEXES (#PCDATA)>
<!ELEMENT RUBBLEMINSPOTS (#PCDATA)>
<!ELEMENT RUBBLEMAXSPOTS (#PCDATA)>
<!ELEMENT RUBBLEMINHEXES (#PCDATA)>
<!ELEMENT RUBBLEMAXHEXES (#PCDATA)>
<!ELEMENT SANDMINSPOTS (#PCDATA)>
<!ELEMENT SANDMAXSPOTS (#PCDATA)>
<!ELEMENT SANDMINHEXES (#PCDATA)>
<!ELEMENT SANDMAXHEXES (#PCDATA)>
<!ELEMENT PLANTEDFIELDMINSPOTS (#PCDATA)>
<!ELEMENT PLANTEDFIELDMAXSPOTS (#PCDATA)>
<!ELEMENT PLANTEDFIELDMINHEXES (#PCDATA)>
<!ELEMENT PLANTEDFIELDMAXHEXES (#PCDATA)>
<!ELEMENT FORTIFIEDMINSPOTS (#PCDATA)>
<!ELEMENT FORTIFIEDMAXSPOTS (#PCDATA)>
<!ELEMENT FORTIFIEDMINHEXES (#PCDATA)>
<!ELEMENT FORTIFIEDMAXHEXES (#PCDATA)>
<!ELEMENT CITYBLOCKS (#PCDATA)>
<!ELEMENT CITYTYPE (#PCDATA)>
<!ELEMENT MOUNTPEAKS (#PCDATA)>
<!ELEMENT MOUNTWIDTHMIN (#PCDATA)>
<!ELEMENT MOUNTWIDTHMAX (#PCDATA)>
<!ELEMENT MOUNTHEIGHTMIN (#PCDATA)>
<!ELEMENT MOUNTHEIGHTMAX (#PCDATA)>
<!ELEMENT MOUNTSTYLE (#PCDATA)>
<!ELEMENT MINCF (#PCDATA)>
<!ELEMENT MAXCF (#PCDATA)>
<!ELEMENT MINFLOORS (#PCDATA)>
<!ELEMENT MAXFLOORS (#PCDATA)>
<!ELEMENT CITYDENSITY (#PCDATA)>
<!ELEMENT THEME (#PCDATA)>
<!ELEMENT STATICMAP (#PCDATA)>
<!ELEMENT MAPNAME (#PCDATA)>
<!ELEMENT XMAP (#PCDATA)>
<!ELEMENT YMAP (#PCDATA)>
<!ELEMENT XBOARD (#PCDATA)>
<!ELEMENT YBOARD (#PCDATA)>

=== MegaMek/MekWars/MekWars/server-dist/data/terrain.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE DOCUMENT SYSTEM "terrain.dtd">
<DOCUMENT>
	<MEGAMEKNETTERRAINDATA>
		<TERRAIN>
			<NAME>Jungle</NAME>
			<ENVIRONMENT>
				<CRATERPROB>0</CRATERPROB>
				<CRATERMINNUM>0</CRATERMINNUM>
				<CRATERMAXNUM>0</CRATERMAXNUM>
				<CRATERMINRADIUS>0</CRATERMINRADIUS>
				<CRATERMAXRADIUS>0</CRATERMAXRADIUS>
				<HILLYNESS>150</HILLYNESS>
				<HILLELEVATIONRANGE>4</HILLELEVATIONRANGE>
				<HILLINVERTPROB>0</HILLINVERTPROB>
				<WATERMINSPOTS>3</WATERMINSPOTS>
				<WATERMAXSPOTS>8</WATERMAXSPOTS>
				<WATERMINHEXES>2</WATERMINHEXES>
				<WATERMAXHEXES>10</WATERMAXHEXES>
				<WATERDEEPPROB>20</WATERDEEPPROB>
				<FORESTMINSPOTS>8</FORESTMINSPOTS>
				<FORESTMAXSPOTS>14</FORESTMAXSPOTS>
				<FORESTMINHEXES>4</FORESTMINHEXES>
				<FORESTMAXHEXES>10</FORESTMAXHEXES>
				<FORESTHEAVYPROB>40</FORESTHEAVYPROB>
				<ROUGHMINSPOTS>0</ROUGHMINSPOTS>
				<ROUGHMAXSPOTS>5</ROUGHMAXSPOTS>
				<ROUGHMINHEXES>1</ROUGHMINHEXES>
				<ROUGHMAXHEXES>2</ROUGHMAXHEXES>
				<ROADPROB>20</ROADPROB>
				<CLIFFPROB>20</CLIFFPROB>
				<RIVERPROB>30</RIVERPROB>
				<ALGORITHM>0</ALGORITHM>
				<SWAMPMINSPOTS>0</SWAMPMINSPOTS>
				<SWAMPMAXSPOTS>0</SWAMPMAXSPOTS>
				<SWAMPMINHEXES>0</SWAMPMINHEXES>
				<SWAMPMAXHEXES>0</SWAMPMAXHEXES>
				<PAVEMENTMINSPOTS>0</PAVEMENTMINSPOTS>
				<PAVEMENTMAXSPOTS>0</PAVEMENTMAXSPOTS>
				<PAVEMENTMINHEXES>0</PAVEMENTMINHEXES>
				<PAVEMENTMAXHEXES>0</PAVEMENTMAXHEXES>
				<ICEMINSPOTS>0</ICEMINSPOTS>
				<ICEMAXSPOTS>0</ICEMAXSPOTS>
				<ICEMINHEXES>0</ICEMINHEXES>
				<ICEMAXHEXES>0</ICEMAXHEXES>
				<RUBBLEMINSPOTS>0</RUBBLEMINSPOTS>
				<RUBBLEMAXSPOTS>0</RUBBLEMAXSPOTS>
				<RUBBLEMINHEXES>0</RUBBLEMINHEXES>
				<RUBBLEMAXHEXES>0</RUBBLEMAXHEXES>
				<SANDMINSPOTS>0</SANDMINSPOTS>
				<SANDMAXSPOTS>0</SANDMAXSPOTS>
				<SANDMINHEXES>0</SANDMINHEXES>
				<SANDMAXHEXES>0</SANDMAXHEXES>
				<PLANTEDFIELDMINSPOTS>0</PLANTEDFIELDMINSPOTS>
				<PLANTEDFIELDMAXSPOTS>0</PLANTEDFIELDMAXSPOTS>
				<PLANTEDFIELDMINHEXES>0</PLANTEDFIELDMINHEXES>
				<PLANTEDFIELDMAXHEXES>0</PLANTEDFIELDMAXHEXES>
				<FORTIFIEDMINSPOTS>0</FORTIFIEDMINSPOTS>
				<FORTIFIEDMAXSPOTS>0</FORTIFIEDMAXSPOTS>
				<FORTIFIEDMINHEXES>0</FORTIFIEDMINHEXES>
				<FORTIFIEDMAXHEXES>0</FORTIFIEDMAXHEXES>
				<!--This sets up the city blocks for auto generated cites this basicly 
					is the number of roads running North South and East West -->
				<CITYBLOCKS>0</CITYBLOCKS>
				<!--Type type GRID, HUB, METRO or NONE. Set to NONE if you do not want 
					a city -->
				<CITYTYPE>NONE</CITYTYPE>

				<!-- Settings to create mountain on your terrain -->
				<MOUNTPEAKS>0</MOUNTPEAKS>
				<MOUNTWIDTHMIN>0</MOUNTWIDTHMIN>
				<MOUNTWIDTHMAX>0</MOUNTWIDTHMAX>
				<MOUNTHEIGHTMIN>0</MOUNTHEIGHTMIN>
				<MOUNTHEIGHTMAX>0</MOUNTHEIGHTMAX>
				<MOUNTSTYLE>0</MOUNTSTYLE>
				<!-- This is a list of the different mount styles. PLAIN = 0; VOLCANO 
					EXTINCT = 1; VOLCANO DORMANT = 2; VOLCANO ACTIVE = 3; SNOWCAPPED = 4; LAKE 
					= 5; -->
				<MINCF>0</MINCF>
				<MAXCF>0</MAXCF>
				<MINFLOORS>0</MINFLOORS>
				<MAXFLOORS>0</MAXFLOORS>
				<CITYDENSITY>50</CITYDENSITY>
			</ENVIRONMENT>
		</TERRAIN>
		<TERRAIN>
			<NAME>Plains</NAME>
			<ENVIRONMENT>
				<CRATERPROB>0</CRATERPROB>
				<CRATERMINNUM>0</CRATERMINNUM>
				<CRATERMAXNUM>0</CRATERMAXNUM>
				<CRATERMINRADIUS>0</CRATERMINRADIUS>
				<CRATERMAXRADIUS>0</CRATERMAXRADIUS>
				<HILLYNESS>150</HILLYNESS>
				<HILLELEVATIONRANGE>4</HILLELEVATIONRANGE>
				<HILLINVERTPROB>0</HILLINVERTPROB>
				<WATERMINSPOTS>3</WATERMINSPOTS>
				<WATERMAXSPOTS>8</WATERMAXSPOTS>
				<WATERMINHEXES>2</WATERMINHEXES>
				<WATERMAXHEXES>10</WATERMAXHEXES>
				<WATERDEEPPROB>20</WATERDEEPPROB>
				<FORESTMINSPOTS>8</FORESTMINSPOTS>
				<FORESTMAXSPOTS>14</FORESTMAXSPOTS>
				<FORESTMINHEXES>4</FORESTMINHEXES>
				<FORESTMAXHEXES>10</FORESTMAXHEXES>
				<FORESTHEAVYPROB>40</FORESTHEAVYPROB>
				<ROUGHMINSPOTS>0</ROUGHMINSPOTS>
				<ROUGHMAXSPOTS>5</ROUGHMAXSPOTS>
				<ROUGHMINHEXES>1</ROUGHMINHEXES>
				<ROUGHMAXHEXES>2</ROUGHMAXHEXES>
				<ROADPROB>20</ROADPROB>
				<CLIFFPROB>20</CLIFFPROB>
				<RIVERPROB>30</RIVERPROB>
				<ALGORITHM>0</ALGORITHM>
				<SWAMPMINSPOTS>0</SWAMPMINSPOTS>
				<SWAMPMAXSPOTS>0</SWAMPMAXSPOTS>
				<SWAMPMINHEXES>0</SWAMPMINHEXES>
				<SWAMPMAXHEXES>0</SWAMPMAXHEXES>
				<PAVEMENTMINSPOTS>0</PAVEMENTMINSPOTS>
				<PAVEMENTMAXSPOTS>0</PAVEMENTMAXSPOTS>
				<PAVEMENTMINHEXES>0</PAVEMENTMINHEXES>
				<PAVEMENTMAXHEXES>0</PAVEMENTMAXHEXES>
				<ICEMINSPOTS>0</ICEMINSPOTS>
				<ICEMAXSPOTS>0</ICEMAXSPOTS>
				<ICEMINHEXES>0</ICEMINHEXES>
				<ICEMAXHEXES>0</ICEMAXHEXES>
				<RUBBLEMINSPOTS>0</RUBBLEMINSPOTS>
				<RUBBLEMAXSPOTS>0</RUBBLEMAXSPOTS>
				<RUBBLEMINHEXES>0</RUBBLEMINHEXES>
				<RUBBLEMAXHEXES>0</RUBBLEMAXHEXES>
				<SANDMINSPOTS>0</SANDMINSPOTS>
				<SANDMAXSPOTS>0</SANDMAXSPOTS>
				<SANDMINHEXES>0</SANDMINHEXES>
				<SANDMAXHEXES>0</SANDMAXHEXES>
				<PLANTEDFIELDMINSPOTS>0</PLANTEDFIELDMINSPOTS>
				<PLANTEDFIELDMAXSPOTS>0</PLANTEDFIELDMAXSPOTS>
				<PLANTEDFIELDMINHEXES>0</PLANTEDFIELDMINHEXES>
				<PLANTEDFIELDMAXHEXES>0</PLANTEDFIELDMAXHEXES>
				<FORTIFIEDMINSPOTS>0</FORTIFIEDMINSPOTS>
				<FORTIFIEDMAXSPOTS>0</FORTIFIEDMAXSPOTS>
				<FORTIFIEDMINHEXES>0</FORTIFIEDMINHEXES>
				<FORTIFIEDMAXHEXES>0</FORTIFIEDMAXHEXES>
				<CITYBLOCKS>0</CITYBLOCKS>
				<CITYTYPE>NONE</CITYTYPE>
				<MINCF>0</MINCF>
				<MAXCF>0</MAXCF>
				<MINFLOORS>0</MINFLOORS>
				<MAXFLOORS>0</MAXFLOORS>
				<CITYDENSITY>50</CITYDENSITY>
				<FXMOD>5</FXMOD>
				<PROBFORESTFIRE>1</PROBFORESTFIRE>
				<PROBFREEZE>10</PROBFREEZE>
				<PROBFLOOD>0</PROBFLOOD>
				<PROBDROUGHT>5</PROBDROUGHT>
				<THEME>SNOW</THEME>
			</ENVIRONMENT>
		</TERRAIN>
		<TERRAIN>
			<NAME>agricultural,water rich,plain</NAME>
			<ENVIRONMENT>
				<CRATERPROB>0</CRATERPROB>
				<CRATERMINNUM>0</CRATERMINNUM>
				<CRATERMAXNUM>0</CRATERMAXNUM>
				<CRATERMINRADIUS>0</CRATERMINRADIUS>
				<CRATERMAXRADIUS>0</CRATERMAXRADIUS>
				<HILLYNESS>150</HILLYNESS>
				<HILLELEVATIONRANGE>4</HILLELEVATIONRANGE>
				<HILLINVERTPROB>0</HILLINVERTPROB>
				<WATERMINSPOTS>3</WATERMINSPOTS>
				<WATERMAXSPOTS>8</WATERMAXSPOTS>
				<WATERMINHEXES>2</WATERMINHEXES>
				<WATERMAXHEXES>10</WATERMAXHEXES>
				<WATERDEEPPROB>20</WATERDEEPPROB>
				<FORESTMINSPOTS>4</FORESTMINSPOTS>
				<FORESTMAXSPOTS>8</FORESTMAXSPOTS>
				<FORESTMINHEXES>2</FORESTMINHEXES>
				<FORESTMAXHEXES>6</FORESTMAXHEXES>
				<FORESTHEAVYPROB>20</FORESTHEAVYPROB>
				<ROUGHMINSPOTS>0</ROUGHMINSPOTS>
				<ROUGHMAXSPOTS>5</ROUGHMAXSPOTS>
				<ROUGHMINHEXES>1</ROUGHMINHEXES>
				<ROUGHMAXHEXES>2</ROUGHMAXHEXES>
				<ROADPROB>20</ROADPROB>
				<CLIFFPROB>20</CLIFFPROB>
				<RIVERPROB>30</RIVERPROB>
				<ALGORITHM>0</ALGORITHM>
				<SWAMPMINSPOTS>0</SWAMPMINSPOTS>
				<SWAMPMAXSPOTS>0</SWAMPMAXSPOTS>
				<SWAMPMINHEXES>0</SWAMPMINHEXES>
				<SWAMPMAXHEXES>0</SWAMPMAXHEXES>
				<PAVEMENTMINSPOTS>0</PAVEMENTMINSPOTS>
				<PAVEMENTMAXSPOTS>0</PAVEMENTMAXSPOTS>
				<PAVEMENTMINHEXES>0</PAVEMENTMINHEXES>
				<PAVEMENTMAXHEXES>0</PAVEMENTMAXHEXES>
				<ICEMINSPOTS>0</ICEMINSPOTS>
				<ICEMAXSPOTS>0</ICEMAXSPOTS>
				<ICEMINHEXES>0</ICEMINHEXES>
				<ICEMAXHEXES>0</ICEMAXHEXES>
				<RUBBLEMINSPOTS>0</RUBBLEMINSPOTS>
				<RUBBLEMAXSPOTS>0</RUBBLEMAXSPOTS>
				<RUBBLEMINHEXES>0</RUBBLEMINHEXES>
				<RUBBLEMAXHEXES>0</RUBBLEMAXHEXES>
				<SANDMINSPOTS>0</SANDMINSPOTS>
				<SANDMAXSPOTS>0</SANDMAXSPOTS>
				<SANDMINHEXES>0</SANDMINHEXES>
				<SANDMAXHEXES>0</SANDMAXHEXES>
				<PLANTEDFIELDMINSPOTS>0</PLANTEDFIELDMINSPOTS>
				<PLANTEDFIELDMAXSPOTS>0</PLANTEDFIELDMAXSPOTS>
				<PLANTEDFIELDMINHEXES>0</PLANTEDFIELDMINHEXES>
				<PLANTEDFIELDMAXHEXES>0</PLANTEDFIELDMAXHEXES>
				<FORTIFIEDMINSPOTS>0</FORTIFIEDMINSPOTS>
				<FORTIFIEDMAXSPOTS>0</FORTIFIEDMAXSPOTS>
				<FORTIFIEDMINHEXES>0</FORTIFIEDMINHEXES>
				<FORTIFIEDMAXHEXES>0</FORTIFIEDMAXHEXES>
				<CITYBLOCKS>0</CITYBLOCKS>
				<CITYTYPE>NONE</CITYTYPE>
				<MINCF>0</MINCF>
				<MAXCF>0</MAXCF>
				<MINFLOORS>0</MINFLOORS>
				<MAXFLOORS>0</MAXFLOORS>
				<CITYDENSITY>50</CITYDENSITY>
			</ENVIRONMENT>
		</TERRAIN>
		<TERRAIN>
			<NAME>agricultural,water rich,uneven</NAME>
			<ENVIRONMENT>
				<CRATERPROB>0</CRATERPROB>
				<CRATERMINNUM>0</CRATERMINNUM>
				<CRATERMAXNUM>0</CRATERMAXNUM>
				<CRATERMINRADIUS>0</CRATERMINRADIUS>
				<CRATERMAXRADIUS>0</CRATERMAXRADIUS>
				<HILLYNESS>400</HILLYNESS>
				<HILLELEVATIONRANGE>7</HILLELEVATIONRANGE>
				<HILLINVERTPROB>0</HILLINVERTPROB>
				<WATERMINSPOTS>2</WATERMINSPOTS>
				<WATERMAXSPOTS>5</WATERMAXSPOTS>
				<WATERMINHEXES>1</WATERMINHEXES>
				<WATERMAXHEXES>6</WATERMAXHEXES>
				<WATERDEEPPROB>20</WATERDEEPPROB>
				<FORESTMINSPOTS>4</FORESTMINSPOTS>
				<FORESTMAXSPOTS>8</FORESTMAXSPOTS>
				<FORESTMINHEXES>2</FORESTMINHEXES>
				<FORESTMAXHEXES>6</FORESTMAXHEXES>
				<FORESTHEAVYPROB>20</FORESTHEAVYPROB>
				<ROUGHMINSPOTS>2</ROUGHMINSPOTS>
				<ROUGHMAXSPOTS>8</ROUGHMAXSPOTS>
				<ROUGHMINHEXES>1</ROUGHMINHEXES>
				<ROUGHMAXHEXES>4</ROUGHMAXHEXES>
				<ROADPROB>10</ROADPROB>
				<CLIFFPROB>20</CLIFFPROB>
				<RIVERPROB>10</RIVERPROB>
				<ALGORITHM>0</ALGORITHM>
				<SWAMPMINSPOTS>0</SWAMPMINSPOTS>
				<SWAMPMAXSPOTS>0</SWAMPMAXSPOTS>
				<SWAMPMINHEXES>0</SWAMPMINHEXES>
				<SWAMPMAXHEXES>0</SWAMPMAXHEXES>
				<PAVEMENTMINSPOTS>0</PAVEMENTMINSPOTS>
				<PAVEMENTMAXSPOTS>0</PAVEMENTMAXSPOTS>
				<PAVEMENTMINHEXES>0</PAVEMENTMINHEXES>
				<PAVEMENTMAXHEXES>0</PAVEMENTMAXHEXES>
				<ICEMINSPOTS>0</ICEMINSPOTS>
				<ICEMAXSPOTS>0</ICEMAXSPOTS>
				<ICEMINHEXES>0</ICEMINHEXES>
				<ICEMAXHEXES>0</ICEMAXHEXES>
				<RUBBLEMINSPOTS>0</RUBBLEMINSPOTS>
				<RUBBLEMAXSPOTS>0</RUBBLEMAXSPOTS>
				<RUBBLEMINHEXES>0</RUBBLEMINHEXES>
				<RUBBLEMAXHEXES>0</RUBBLEMAXHEXES>
				<SANDMINSPOTS>0</SANDMINSPOTS>
				<SANDMAXSPOTS>0</SANDMAXSPOTS>
				<SANDMINHEXES>0</SANDMINHEXES>
				<SANDMAXHEXES>0</SANDMAXHEXES>
				<PLANTEDFIELDMINSPOTS>0</PLANTEDFIELDMINSPOTS>
				<PLANTEDFIELDMAXSPOTS>0</PLANTEDFIELDMAXSPOTS>
